### ISSUE TITLE
请教一些问题

### ISSUE THREAD

**Issue by johnmai-dev** [weizengreal/anonymou#1]
anonymou/application/index/controller/Index.php中的`$code = Request::instance()->get("code",false);`  这里的code是微信oauth的code吗？

**Comment by weizengreal** [comment]
是的，逻辑是使用了微信静默授权实现用户确身份标识。

**Comment by johnmai-dev** [comment]
那是怎么做得微信静默授权的？oauth不是要认证公众号的吗？

**Comment by johnmai-dev** [comment]
可以给我讲讲思路吗？

**Comment by johnmai-dev** [comment]
你是用一个认证的服务号来做授权？然后放到微校上，这样就可以在其他公号上使用oauth？

**Comment by weizengreal** [comment]
刚刚查了下，根目录下extend里面缺少两个组件，当时git上传的时候默认给我加了个.gitignore，所以都没上传上去，现在ok了。

**Comment by johnmai-dev** [comment]
用户不用关注你那个服务号也可以通过oauth 去获取用户标识？

**Comment by weizengreal** [comment]
是的，这些部分应该属于微信开发范围，可以参考链接： https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842 。
